name: CI/CD Pipeline

on:
  push:
    branches:
      - "main"
      - "develop"
      - "feature/**"
  pull_request:

jobs:
  test:
    name: Run Tests & Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Test (CI)
        run: npm test

      - name: Security Scan (CS)
        run: npm audit --audit-level=moderate

  docker:
    name: Build Docker Image (CD)
    runs-on: ubuntu-latest
    needs: test   # hanya jalan kalau test sukses

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t todo-api .